language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
    - composer require symfony/security-bundle:${SYMFONY_VERSION}
    - composer require symfony/console:${SYMFONY_VERSION}
    - composer require symfony/dependency-injection:${SYMFONY_VERSION}
    - composer require phpunit/phpunit:4.*
    - composer require mikey179/vfsStream:1.*
