language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
  - SYMFONY_VERSION="2.5.*"
  - SYMFONY_VERSION="2.6.*"

before_script:
  - composer selfupdate
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
